export const PathAPI = {
  uploadFormdata: '/admin/upload/image/single/',
  login: '/admin/user/login/',
  constant: '/config/constants/',
  user: '/admin/user/info',
  question: '/admin/question/',
  tag: '/admin/tags/',
  course: '/admin/course',
  courseHM: '/admin/course/hm',
  subject: '/admin/subject',
  class: '/admin/class',
  grade: '/admin/schoolLevel',
  report: '/admin/report',
  history: '/admin/history',
  knowledgeUnit: '/admin/knowledgeUnit',
  test: '/admin/test',
  baikiemtra: '/admin/baikiemtra',
  submitTest: '/api/v1/admin/exam/test',
  contest: '/admin/contest/100',
  company: '/admin/company/',
};
